//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace YumCity_Migrations.HelperClasses
{
	/// <summary>Field Creation Class for entity CategoryEntity</summary>
	public partial class CategoryFields
	{
		/// <summary>Creates a new CategoryEntity.Data field instance</summary>
		public static EntityField2 Data { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Data); }}
		/// <summary>Creates a new CategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Id); }}
		/// <summary>Creates a new CategoryEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.IsActive); }}
	}

	/// <summary>Field Creation Class for entity IngredientEntity</summary>
	public partial class IngredientFields
	{
		/// <summary>Creates a new IngredientEntity.Data field instance</summary>
		public static EntityField2 Data { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.Data); }}
		/// <summary>Creates a new IngredientEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.Id); }}
		/// <summary>Creates a new IngredientEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.IsActive); }}
		/// <summary>Creates a new IngredientEntity.RecipeId field instance</summary>
		public static EntityField2 RecipeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.RecipeId); }}
	}

	/// <summary>Field Creation Class for entity InstructionEntity</summary>
	public partial class InstructionFields
	{
		/// <summary>Creates a new InstructionEntity.Data field instance</summary>
		public static EntityField2 Data { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.Data); }}
		/// <summary>Creates a new InstructionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.Id); }}
		/// <summary>Creates a new InstructionEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.IsActive); }}
		/// <summary>Creates a new InstructionEntity.RecipeId field instance</summary>
		public static EntityField2 RecipeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.RecipeId); }}
	}

	/// <summary>Field Creation Class for entity RecipeEntity</summary>
	public partial class RecipeFields
	{
		/// <summary>Creates a new RecipeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.Id); }}
		/// <summary>Creates a new RecipeEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.IsActive); }}
		/// <summary>Creates a new RecipeEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.Title); }}
		/// <summary>Creates a new RecipeEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity RecipeCategoryEntity</summary>
	public partial class RecipeCategoryFields
	{
		/// <summary>Creates a new RecipeCategoryEntity.Data field instance</summary>
		public static EntityField2 Data { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeCategoryFieldIndex.Data); }}
		/// <summary>Creates a new RecipeCategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeCategoryFieldIndex.Id); }}
		/// <summary>Creates a new RecipeCategoryEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeCategoryFieldIndex.IsActive); }}
		/// <summary>Creates a new RecipeCategoryEntity.RecipeId field instance</summary>
		public static EntityField2 RecipeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeCategoryFieldIndex.RecipeId); }}
	}

	/// <summary>Field Creation Class for entity RefreshTokenEntity</summary>
	public partial class RefreshTokenFields
	{
		/// <summary>Creates a new RefreshTokenEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RefreshTokenFieldIndex.Id); }}
		/// <summary>Creates a new RefreshTokenEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RefreshTokenFieldIndex.IsActive); }}
		/// <summary>Creates a new RefreshTokenEntity.TimeCreated field instance</summary>
		public static EntityField2 TimeCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RefreshTokenFieldIndex.TimeCreated); }}
		/// <summary>Creates a new RefreshTokenEntity.TimeExpires field instance</summary>
		public static EntityField2 TimeExpires { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RefreshTokenFieldIndex.TimeExpires); }}
		/// <summary>Creates a new RefreshTokenEntity.Token field instance</summary>
		public static EntityField2 Token { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RefreshTokenFieldIndex.Token); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.IsActive); }}
		/// <summary>Creates a new UserEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Name); }}
		/// <summary>Creates a new UserEntity.PasswordHash field instance</summary>
		public static EntityField2 PasswordHash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordHash); }}
		/// <summary>Creates a new UserEntity.RefreshTokenId field instance</summary>
		public static EntityField2 RefreshTokenId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.RefreshTokenId); }}
	}
	

}